### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by HalFinneyIsMyHomeBoy** [dieqohc/HSM-to-XPRV-recovery-tool#1]
Can't install requirements.  I've tried upgrading pip, reinstalling pip and installing numpy with -no-binary flag.  Keep getting stuck when trying to install requirements.  OS = Ubuntu 22.04.2 LTS

![image](https://github.com/dieqohc/HSM-to-XPRV-recovery-tool/assets/1430502/f99cc6c2-d9a1-40f5-9207-8097d6a8c5af)

**Comment by HalFinneyIsMyHomeBoy** [comment]
[error.txt](https://github.com/dieqohc/HSM-to-XPRV-recovery-tool/files/13442727/error.txt)

Here is error log for details

**Comment by dieqohc** [comment]
Appreciate the information, the issue seems to have been solved already, the problem was that I probably ran a 'pip freeze' without the activated venv saving all my windows packages in the requirements file, which was unnecessary, produced errors and bloated the installation.

1. If possible try to remove the downloaded drectory, and clone it or download it again, and follow the common procedure.

Let me know in order to close this issue.

**Comment by HalFinneyIsMyHomeBoy** [comment]
I deleted the venv folder and the repo.  Re-cloned and everything works now.
